name: publish docker image

on:
  push:
    branches: [ 'main' ]

jobs:
  image-publish:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@v1.1
    with:
      image_namespace: wipacrepo
      image_name: wipac-dev-actions-testbed-docker
      mode: BUILD
    secrets:
      registry_token: ${{ secrets.GITHUB_TOKEN }}
