name: publish docker image


on:
  push:
    branches: [ 'main' ]


jobs:
  image-publish:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@image-publish
    with:
      image: ghcr.io/wipacrepo/wipac-dev-actions-testbed-docker
      mode: BUILD
    secrets:
      registry_token: ${{ secrets.GITHUB_TOKEN }}
