name: publish docker image

on:
  push:
    branches: [ 'main' ]
    tags: [ '**' ]
  workflow_dispatch:
    inputs:
      tag_override:
        description: 'the tag to publish and possibly overwrite'
        default: 'dev'
        required: false

jobs:
  image-publish:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@publish_tag_override
    with:
      image_namespace: wipacrepo
      image_name: wipac-dev-actions-testbed-docker
      mode: BUILD
      publish_tag_override: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_override || '' }}
