name: publish docker image

on:
  push:
    branches: [ 'main' ]


jobs:

  image-publish:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@image-publish
    with:
      image: wipac/wipac-dev-actions-testbed-docker
      mode: BUILD
    secrets:
      registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_token: ${{ secrets.DOCKERHUB_TOKEN }}
